[package]
name = "log4rs"
version = "0.4.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "A highly configurable multi-output logging implementation for the `log` facade"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/log4rs"
documentation = "https://sfackler.github.io/log4rs/doc/v0.4.3/log4rs"

[features]
yaml = ["serde_yaml"]
json = ["serde_json"]

[dependencies]
antidote = "0.1"
chrono = "0.2"
crossbeam = "0.2.9"
kernel32-sys = "0.2"
libc = "0.2"
log = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde-value = "0.4"
typemap = "0.3"
winapi = "0.2"
serde_json = { version = "0.9", optional = true }
serde_yaml = { version = "0.6", optional = true }
toml = { version = "0.3", optional = true, default_features = false, features = ["serde"] }
